Asd 1193
BearGroup/amazon-payments-magento-2-plugin pull request #88
Opened 2024-05-24 16:21 UTC by jaybeckr

Fixes # .

#### Additional details about this PR

2024-05-24 17:19 UTC, MicheleBeargroup requested changes
Looks good except for some stylistic/defensive code suggestions.

2024-05-24 17:19 UTC, MicheleBeargroup commented on Controller/Checkout/PlaceOrder.php
> +            if ($result['success']) {
In general, when calling a key on an array, I would set it to a variable ahead of the check - i.e. $resultvar = $result['success'] ?? false;

2024-05-24 17:19 UTC, MicheleBeargroup commented on Cron/CleanUpIncompleteSessions.php
> +    private function processTransaction(array $transactionData)
General comment - is there a good argument for setting things private? Protected allows other developers to extend for their project.

2024-05-24 17:19 UTC, MicheleBeargroup commented on Cron/CleanUpIncompleteSessions.php
> +            switch ($amazonSession['statusDetails']['state']) {
Another case where I would pre-set the key check to a variable prior to calling a switch on it. That way if one of the keys is missing or has a different than expected value, it will at least go to the default case rather than throwing an error during cron.  i.e. $status = $amazonSession['statusDetails']['state'] ?? '';

2024-05-24 17:19 UTC, MicheleBeargroup commented on Helper/Transaction.php
Again - wondering if there is a reason to set things private rather than protected.

2024-05-24 17:21 UTC, jajajaime requested changes

2024-05-24 17:21 UTC, jajajaime commented on Cron/CleanUpIncompleteSessions.php
> +                    $chargeId = $amazonSession['chargeId'];
This is not needed.

2024-05-24 17:21 UTC, jajajaime commented on Cron/CleanUpIncompleteSessions.php
> +    private function processTransaction(array $transactionData)
Should this method also add a log if the cleanup was successful for session id x?

2024-05-24 17:21 UTC, jajajaime commented on Helper/Transaction.php
> +
Remove extra space

2024-05-28 14:29 UTC, jaybeckr commented on Controller/Checkout/PlaceOrder.php
> +            if ($result['success']) {
This is a good call out, the code is following a pattern used elsewhere so not going to change it globally at this moment.

2024-05-28 15:49 UTC, jajajaime commented on Cron/CleanUpIncompleteSessions.php
> +                    $this->logger->info('Amazon Session Canceled, cancelling order and closing transaction');
Missed using the `$logMessage` variable here

2024-05-28 15:55 UTC, MicheleBeargroup approved these changes

2024-05-28 16:29 UTC, jajajaime approved these changes

2024-05-30 19:36 UTC, merged